[project]
name = "imageanalysis-pipeline"
version = "1.1.1"
description = "Analysis pipelines for fluorescent microscopic images, mainly time sequences, that is capable of pre-process, segment, track and get data of single cells."
readme = "README.md"
authors = [
    {name = "Benoit Thomas Roux", email = "benoit.roux@gmail.com"},
    {name = "Fabian Gregory Dehne", email = "fabiang.dehne@gmail.com"},
    {name = "Raphael David FEURSTEIN", email = "raphael.feurstein@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "cellpose[gui]<4",
    "ipython>=9.2.0",
    "ipywidgets>=8.1.7",
    "markupsafe<3.0",
    "matplotlib>=3.10.1",
    "nd2>=0.10.3",
    "opencv-python>=4.11.0.86",
    "pandas[parquet]>=2.2.3",
    "pyqt6>=6.9.0",
    "pystackreg>=0.2.8",
    "pytorch-lightning>=2.5.1.post0",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "smo>=2.0.2",
    "tifffile>=2025.3.30",
    "torch>=2.6.0",
    "torch-geometric>=2.6.1",
    "torch-scatter",
    "torch-sparse",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
]

[project.scripts]
imageanalysis-pipeline = "pipeline:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["imageanalysis"]

[tool.uv.sources]
torch-sparse = [
    {url = "https://data.pyg.org/whl/torch-2.6.0+cu124/torch_sparse-0.6.18+pt26cu124-cp312-cp312-linux_x86_64.whl", marker = "sys_platform == 'linux'"},
    
    {url = "https://data.pyg.org/whl/torch-2.6.0+cu124/torch_sparse-0.6.18+pt26cu124-cp312-cp312-win_amd64.whl", marker = "sys_platform == 'win32'"}
]
torch-scatter = [
    {url = "https://data.pyg.org/whl/torch-2.6.0+cu124/torch_scatter-2.1.2+pt26cu124-cp312-cp312-linux_x86_64.whl", marker = "sys_platform == 'linux'"},
    
    {url = "https://data.pyg.org/whl/torch-2.6.0+cu124/torch_scatter-2.1.2+pt26cu124-cp312-cp312-win_amd64.whl", marker = "sys_platform == 'win32'"}
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu124"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]

